### ISSUE TITLE
[Bug] I can't find it in the HACS repositories

### ISSUE THREAD

**Issue by zjuanma** [tomaae/homeassistant-portainer#11]
## Describe the issue
I can't find it in the HACS repositories

## How to reproduce the issue
Go to HACS and try to find it.

**Comment by nicholaswilde** [comment]
Perhaps the directions can say to add as a custom repository in HACS for now until the PR is merged?

**Comment by tomaae** [comment]
well, this repository is work in progress and is not shown or posted anywhere. no idea how so many people managed to find it.
it is set like this to prepare for it being published by hacs.

**Comment by caublet** [comment]
cant find it in HACS either..

**Comment by caublet** [comment]
> 

there is work to be done to get this PR  accepted!

**Comment by kasparsd** [comment]
For anyone looking for a way to add this repository before it is available from "the store", there is the Custom repositories option on the home screen of HACS Integrations screen under `/hacs/integrations`:

![custom-repos](https://github.com/tomaae/homeassistant-portainer/assets/169055/3ca92c38-8777-4b1c-87d2-2b15f09e0c69)

where you would add `https://github.com/tomaae/homeassistant-portainer` and mark it as `Integration`:

![custom-repos-add](https://github.com/tomaae/homeassistant-portainer/assets/169055/adaa57f1-8f62-48c7-b205-137560cf0d81)

**Comment by tomaae** [comment]
it is just waiting game really. in hacs they approve only few oldest requests per week now.
it used to always approved within a week with all my previous integrations, but that changed.
