### ISSUE TITLE
[Bug] - no sensors in HA

### ISSUE THREAD

**Issue by jboesh** [tomaae/homeassistant-portainer#12]
Hi, I followed the steps, also with the access token in Portainer. 
When I add the integration configuration it works fine, but I don't see any sensors in HA.

Am I missing something or does the integration perhaps not (yet) work with the latest HA/Portainer versions?

There are no logs generated in HA.

Thanks

**Versions**
HA: 2019.1
Portainer 1.25.0

The issue:
![image](https://github.com/tomaae/homeassistant-portainer/assets/71582854/ad91e0db-5fdd-45ad-b7f5-90c03579a305)

**Comment by tomaae** [comment]
its a problem with 2023.9.X. but you should see messages in HA log.

**Comment by jboesh** [comment]
> its a problem with 2023.9.X. but you should see messages in HA log.

It is something you can fix?

**Comment by tomaae** [comment]
yes of course, but it will take some time. I have to update all integrations.

**Comment by kasparsd** [comment]
Not sure if this is helpful but it is reporting the following error in the logs:

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:621
Integration: Sensor (documentation, issues)
First occurred: 12:29:20 (18 occurrences)
Last logged: 12:30:13

portainer: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://IP_HERE:3002', 'connections': {('portainer', 'Portainer_Endpoints')}, 'default_manufacturer': 'Portainer', 'default_name': 'Portainer Endpoints', 'identifiers': {('portainer', 'Portainer_Endpoints')}, 'sw_version': ''} for 'portainer' config entry: device info needs to either describe a device, link to existing device or provide extra information.
portainer: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://IP_HERE:3002', 'connections': {('portainer', 'Portainer_local')}, 'default_manufacturer': 'Docker', 'default_name': 'Portainer local', 'identifiers': {('portainer', 'Portainer_local')}, 'sw_version': '20.10.22-qnap7'} for 'portainer' config entry: device info needs to either describe a device, link to existing device or provide extra information.
```

**Comment by tomaae** [comment]
yes, that is related.

**Comment by tomaae** [comment]
fixed in new release
