### ISSUE TITLE
[Bug] Cannot configure Integration through a FQDN, I get a "No response from host" error

### ISSUE THREAD

**Issue by B4dC4rd** [tomaae/homeassistant-portainer#19]
## Describe the issue

Cannot configure Integration through a FQDN, I get a "No response from host" error

## How to reproduce the issue

Initial configuration
Host : https://<Fully Qualified Domain Name/ (Tried with or without 443 port)
Use SSL : true (tried with or without)
Verify SSL : true (tried with or without)

## Expected behavior

Sucesfull configuration

## Software versions

All fields in this sections are required.

 - Version | core-2023.9.3
 - Installation Type | Home Assistant OS
 - Portainer integration version: 1.0.2
 - Portainer software version: 2.19.1

## Additional context

Portainer is running in a docker container
I can acccess it with no issue through the Fully Qualified Domain on the local network and from internet.

**Comment by tomaae** [comment]
thats not integration issue, but infrastructure issue.
check you network settings on ha and dns.

**Comment by B4dC4rd** [comment]
Hi @tomaae 

I can connect with a grocy instance in HTTPS with no issue. there must be some thing special with Portainer?

I'm getting log warnings: 

This error originated from a custom integration.

Logger: py.warnings
Source: custom_components/portainer/api.py:82
Integration: Portainer (documentation, issues)
First occurred: 18:13:25 (472 occurrences)
Last logged: 20:11:13

/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'redacted IP'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings warnings.warn(

**Comment by tomaae** [comment]
that is just a warning that you are using bad certificate, should not affect anything
