### ISSUE TITLE
[Bug] Entities not working (portainer-agent stopped)

### ISSUE THREAD

**Issue by lucidnx** [tomaae/homeassistant-portainer#22]
## Describe the issue
After adding integration, all entities are unavailable when using portainer-agent

1. Have 2 separate docker hosts with portainer and portainer-agent installed on both
2. configure connections:
from portainer1 to docker1 using local socket (default), portainer1 to docker2 using portainer-agent2
from portainer2 to docker2 using local socket (default), portainer2 to docker1 using portainer-agent1
3. stop portainer agents on both hosts
4. configure portainer integration with portainer1

## Expected behavior
Working entities that are on docker1, when integration is configured to use portainer1.

## Software versions
 - Home Assistant version: 2023.10.5
 - Portainer integration version: v1.0.2
 - Portainer software version: CE 2.18.4

## Additional context
Weird is that if I start portainer-agent on docker2, it will immedialy start working for both, docker1 and docker2 containers.

**Comment by tomaae** [comment]
not sure how can I help here. from what I know, portainer agent is separate software that exposes docker api.
you can have a look at errors in your ha log and test if portainer itself is working and that you can see status of your containers.

**Comment by lucidnx** [comment]
portainer is working, this is really weird. in HA there's logged error: Portainer portainer1 unable to fetch data "endpoints/3/docker/containers/json" (502)
