### ISSUE TITLE
[Bug] 200 Error

### ISSUE THREAD

**Issue by mayorgergich** [tomaae/homeassistant-portainer#25]
## Describe the issue

When attempting to connect to my remote box via portainer.mywebsite.com and issuing the access token the setup screen replies with 200 and doesn't move forward.

## Software versions

 - Home Assistant version:  2023.11.3
 - Portainer integration version:  1.0.2
 - Portainer software version:

**Comment by mayorgergich** [comment]
Bumping this again. Would be super helpful.

**Comment by tomaae** [comment]
try running integration in debug, not sure what is happening there.
my guess is that portainer is not responding correctly.
