### ISSUE TITLE
Containers with the same name keep being recreated[Bug]

### ISSUE THREAD

**Issue by KuraiAndras** [tomaae/homeassistant-portainer#27]
## Describe the issue
I have multiple containers shown as sensors, and most of them are unavailable and could only be deleted manually - the problem is that I noticed it late and now I have ~1400 sensors listed in HA and it slows things down a bit.

To be clear: this is connected to Portainer with 2 docker standalone environments and running around 30 containers - definitely not in the thousands.

## How to reproduce the issue
🤷‍♂️

## Expected behavior
Containers as sensors don't get duplicated

## Screenshots
![image](https://github.com/tomaae/homeassistant-portainer/assets/19240945/f8c51599-c522-46fb-855b-8814f72c8f7e)
![image](https://github.com/tomaae/homeassistant-portainer/assets/19240945/0dc5eb9e-d42f-4c62-82cd-e0aebd44933c)
![image](https://github.com/tomaae/homeassistant-portainer/assets/19240945/f690bde0-00c7-4eb6-afe5-e1c4c7f66f06)

## Software versions
 - Home Assistant version: 2024.1.3
 - Portainer integration version: V1.0.2
 - Portainer software version: 2.19.4 BE

## Diagnostics data
🤷‍♂️

## Traceback/Error logs
🤷‍♂️

## Additional context
I am runnig Portainer Business Edition - the problem seems to be is that when I update a stack using Portainer BE and select Re-pull image and redeploy 
![image](https://github.com/tomaae/homeassistant-portainer/assets/19240945/f5326115-0a01-46f4-9728-963a71584c59)
The number of entities goes up by the number of containers in the stack - indicating that this is caused by portainer stopping containers, pulling the latest image and then re deploying them. It also seems that additional container senors in the integration get a new index when they get recreated. For example:
![image](https://github.com/tomaae/homeassistant-portainer/assets/19240945/6d65b26b-e4b3-45bc-b90e-c3a5a482ff50)
![image](https://github.com/tomaae/homeassistant-portainer/assets/19240945/cd9db825-7a5c-4048-943f-4cbe635af4ab)

**Comment by tomaae** [comment]
duplicate #7
