### ISSUE TITLE
[Feature] Rename sensors based on environment name

### ISSUE THREAD

**Issue by c3p0vsr2d2** [tomaae/homeassistant-portainer#29]
## Is your feature request related to a problem? Please describe.

I have multple environments in Portainer, each for different endpoints.
There are common containers across all these endpoints, for example telegraf/glances/etc.
For containers with the same names across different environments, this integration creates similar name sensors, like 
sensor.telegraf_xx_1, sensor.telegraf_xx_2, etc. This becomes difficult to maintain in HA.

## Describe the solution you'd like

Append environment name to the sensor entity, 
sensor.environment_one_telegraf, sensor.environment_two_telegraf, etc

**Comment by tomaae** [comment]
hmm, would this work? what about migrating entities between environments?

**Comment by c3p0vsr2d2** [comment]
not sure what you mean ... (sorry portainer/docker noob)
telegraf/glances/etc are containers per physical endpoint - so the corresponding entities would not need to be migrated between environments/endpoints
