### ISSUE TITLE
[Question] No response from host.

### ISSUE THREAD

**Issue by RatWolf** [tomaae/homeassistant-portainer#32]
Hello together,
I'm running my Homeassistant as an Container and installed HACS.
Now I want to control my other containers with Homeassistant and found your Addon.
When I tried to connect to docker, it says:
unable to fetch data "endpoints" (no_response)

So I activated the debug and he says:
query: endpoints, get, {}
and in the second line:
unable to fetch data "endpoints" (no_response)

I've tried to use https and without, tried to add "/api/endpoints/2/" and other things.
I even removed the docker from the swarm and it didn't helped.
I have no clue how i could go further.

Hopefully, somebody could help me.
Thanks, before.
Greetings
Ralf

**Comment by RatWolf** [comment]
I'm not sure if it's a bug or a question, if this is a bug, maybe I, should it recreate that someone reacts?

**Comment by vinkmr** [comment]
@RatWolf 
I was in the same boat as you. But just figured it out by looking at the source code.
You will want to provide the ip address of the system where you have portainer running along with the port in the field for ˋhostˋ. Also, check the ˋUse SSLˋ option box. See image below for reference.
![SmartSelect_20240409_232954_Home Assistant.jpg](https://github.com/tomaae/homeassistant-portainer/assets/42782192/1dc1e6cc-3cb2-4203-965c-28e2d379046b)

**Comment by RatWolf** [comment]
First, thanks for your reply @vinkmr .
Sadly, I've also tried that and it doesn't work.
The interesting thing ist, the only Packages from my HA to my Docker is this (IP changed):
19:01:08.430519 ARP, Request who-has 10.0.0.1 tell 10.0.0.2, length 46

**Comment by vinkmr** [comment]
@RatWolf I am having a little trouble understanding your question. Correct me if I understand your situation wrong. 

You have homeassistant(HA) running as a docker container,
and you also have portainer running as docker container,
you have forwarded port 9443 for the portainer container to the some port on the host machine.
Now when you provide <host_IP>:<some_port> in the ˋHost field, along with the API key you have generated on portainer, and after turning on "Check SSL" option on the HA portainer integration, you are still getting "no_response"?

Are you able to login to your portainer instance from the machine running HA via a browser?

**Comment by tomaae** [comment]
check if you can reach it from HA directly. its likely that they cant communicate.

**Comment by colinLH** [comment]
@RatWolf I'm having the same problem as you before. You need to check the following:
1. Make sure you have installed Portainer container, running on 9443 port and you can reach GUI through the browser like https://<ip address>:9443. (http should set the redirect rule)

2. Make sure you have register an account and generate the access token. (If not, following this guide: https://github.com/tomaae/homeassistant-portainer 【#Get portainer access token】)

3. Make sure you have downloaded the Portainer integration from the HACS

4. 【The most important step】Reboot the HA and do the things as the vinkmr said aforementioned.

**Comment by RatWolf** [comment]
Sorry, I Missed the last answers, tomorrow I will check all the information and give an answer.

**Comment by RatWolf** [comment]
@vinkmr since the HA is only a container on the same machine I have no Browser on the “Machine”.
@tomaae how could i check that? "Docker exec -it homeassistant ping" ?
@colinLH everything done, but still wont work :(

**Comment by tomaae** [comment]
from portainer, you can execute shell in container and run commands there. you need to check both ping and port accessibility from HA

**Comment by RatWolf** [comment]
When I tried that, I've got:
Unable to retrieve image details
So I couldn't connect to the console of the container :(

**Comment by tomaae** [comment]
try different shell

**Comment by RatWolf** [comment]
idk how, so I'm fine with it that it will never work.

**Comment by RatWolf** [comment]
idk how, so I'm fine with it that it will never work.
