### ISSUE TITLE
[Bug] all Endpoints shown offline if one Endpoint is offline

### ISSUE THREAD

**Issue by Ajimaru** [tomaae/homeassistant-portainer#34]
## Describe the issue

HA shows both Endpoints as offline if one Endpoint is offline.

## How to reproduce the issue

1. Shutdown one Endpoint, here the Endpoint "PBS":
![Bildschirmfoto 2024-04-01 um 09 33 27](https://github.com/tomaae/homeassistant-portainer/assets/38381946/26fb7fa0-65c9-4623-9591-4a7f82bbc02e)

2. Click on Portainer Card:
![Bildschirmfoto 2024-04-01 um 09 34 07](https://github.com/tomaae/homeassistant-portainer/assets/38381946/c8463dd9-ca1d-4cdb-a32e-41c89664f269)
![Bildschirmfoto 2024-04-01 um 09 13 15](https://github.com/tomaae/homeassistant-portainer/assets/38381946/02fc98b1-6923-4878-8236-c193632ffa9a)
![Bildschirmfoto 2024-04-01 um 09 13 04](https://github.com/tomaae/homeassistant-portainer/assets/38381946/319c3463-be8a-4d34-9f9f-bf09eee50639)

3. Start the previously stopped Endpoint:
![Bildschirmfoto 2024-04-01 um 09 12 21](https://github.com/tomaae/homeassistant-portainer/assets/38381946/53182ac1-41ad-4d1a-aeab-be6c4fb9bfbb)
![Bildschirmfoto 2024-04-01 um 09 12 46](https://github.com/tomaae/homeassistant-portainer/assets/38381946/6902adda-0ee5-44c4-a712-8552c6629bfa)

## Expected behavior

HA Portainer integration shows only the offline Endpoint as offline.

## Software versions

- Home Assistant version: 
   Core 2024.3.3
   Supervisor 2024.03.1
   Operating System 12.1
   Frontend 20240307.0
 
- Portainer integration version: v1.0.2

- Portainer software version:
   Endpoint Homeserver 24.0.5
   Endpoint PBS              25.0.3

## Additional context

The second integration is on another system, witch is online only every 3 days.

**Comment by uberoptix** [comment]
I also see all my sensors as Unavailable. Not sure if this is the reason why, but have tried all the usual remediations, including rebooting, uninstalled and reinstalled the plugin, and generating a new API key.

**Comment by Ajimaru** [comment]
@tomaae  any sugesstions?

**Comment by pdsccode** [comment]
Experiencing the same issue at the moment. In preparation of a move I have shut down one of my Portainer servers already. Now everything shows as unavailable within Home Assistant.

**Comment by mhosse** [comment]
Experienced the same issue and found a fix.

**Comment by mhosse** [comment]
bump
