### ISSUE TITLE
[Feature] Re-Configure the integration

### ISSUE THREAD

**Issue by dapuzz** [tomaae/homeassistant-portainer#4]
Hello
Is it possible to view or change the configuration after the initial setup? 
Or should I delete the integration and add back again?

Here attached the screen just to let me explain what am I referring to:
![image](https://github.com/tomaae/homeassistant-portainer/assets/45406499/62e46413-7b71-46ab-bcc5-314f6355cddb)

Thanks!!

**Comment by tomaae** [comment]
configure is for additional settings, not base configuration. there are no additional settings in portainer integration yet.
