### ISSUE TITLE
[Question] unable to re add portainer integration

### ISSUE THREAD

**Issue by demonkazuya** [tomaae/homeassistant-portainer#47]
Hi,

Was able to add the integration before and removed it since I was having an issue with duplicate instance on Home Assistant (my fault). now when I try to add it bac it gives me this error:

![image](https://github.com/user-attachments/assets/9e1c9048-a986-4a4b-b3b4-e3e7a0d24223)

tried port 9443 and port 9000, https and http uncheck on SSL verify Cert. Tried to generate mutiple API but still the same issue. Is there anything else I can do?

Also both HA and Portainer is running on the same machine. Thanks!

**Comment by thesaulsbooks** [comment]
"If you require HTTP port 9000 open for legacy reasons, add the following to your docker run command:

-p 9000:9000"

This is needed to do the "server:9000" the http port is not turned on. Steps below I just did:

docker stop portainer

docker rm portainer

docker pull portainer/portainer-ce:2.21.4

docker run -d -p 8000:8000 -p 9000:9000 -p 9443:9443 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:2.21.4

**Comment by PavelD** [comment]
Hi, don't prefix host with http(s):// and try it again.

**Comment by tomaae** [comment]
yea, host should never contain protocol prefix. if that does not work, that means you have networking issue.
