### ISSUE TITLE
[Feature] Environment as attribute

### ISSUE THREAD

**Issue by IAmTheMilkManMyMilkIsDelicious** [tomaae/homeassistant-portainer#5]
## Is your feature request related to a problem? Please describe.

I want to have a list of my containers and their environments visible in home assistant. 

## Describe the solution you'd like

An attribute value for every entity called `environment` which would match the environment name the container is in

**Comment by tomaae** [comment]
not sure thats suitable. envinroment variables can be really long.

**Comment by IAmTheMilkManMyMilkIsDelicious** [comment]
I don't mean environment variables, I just mean the name of the portainer environment (or endpoint) that the container is in.

**Comment by tomaae** [comment]
can you show it to me, so we are on same page?

**Comment by IAmTheMilkManMyMilkIsDelicious** [comment]
I've made a PR that I hope explains it better

https://github.com/tomaae/homeassistant-portainer/pull/6

**Comment by tomaae** [comment]
ah right, now I know what it is. sure, no problem there.
thanks for PR
